  
{{- if .Values.ruler.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-ruler
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: ruler
{{- end }}
