  
{{- if .Values.storegateway.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-storegateway
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: storegateway
{{- end }}
