  
{{- if .Values.querier.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-querier
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier
{{- end }}
