{{- if (include "thanos.createObjstoreConfigmap" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thanos.fullname" . }}-objstore-configmap
  labels: {{- include "thanos.labels" . | nindent 4 }}
data:
  objstore.yml: |-
    {{- include "thanos.tplValue" (dict "value" .Values.objstoreConfig "context" $) | nindent 4 }}
{{ end }}
