  
{{- if .Values.bucketweb.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thanos.fullname" . }}-bucketweb
  labels: {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: bucketweb
{{- end }}
